"""Add gender and target fields

Revision ID: 9ff9531017f6
Revises: 
Create Date: 2025-02-08 13:48:39.175322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ff9531017f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_record')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('target_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_bmi', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_body_fat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_lean_mass', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('target_lean_mass')
        batch_op.drop_column('target_body_fat')
        batch_op.drop_column('target_bmi')
        batch_op.drop_column('target_weight')
        batch_op.drop_column('gender')

    op.create_table('weight_record',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('weight', sa.FLOAT(), nullable=False),
    sa.Column('body_fat', sa.FLOAT(), nullable=True),
    sa.Column('memo', sa.TEXT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('target_weight', sa.FLOAT(), nullable=True),
    sa.Column('target_body_fat', sa.FLOAT(), nullable=True),
    sa.Column('star_rating', sa.INTEGER(), nullable=True),
    sa.Column('rating_shown', sa.BOOLEAN(), nullable=True),
    sa.Column('shared_count', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
